{"name": "一键呼救列表导出", "status": "broken", "statusDetails": {"message": "TypeError: 'NoneType' object is not subscriptable", "trace": ">   ???\nE   TypeError: 'NoneType' object is not subscriptable\n\nD:\\work\\jishiyu\\Interface_Test\\test_case\\opsPC\\conftest.py:10: TypeError"}, "start": 1692597242909, "stop": 1692597242909, "uuid": "3c4597f4-3d34-4606-9e79-0b90bedbd11f", "historyId": "8570400d3fd747d3d4b595ad4ace277c", "testCaseId": "c7a2f62447b689462dd3eea09ce33900", "fullName": "opsPC.test_emergency#test_elevator_call_record_export_001", "labels": [{"name": "feature", "value": "运维管理平台"}, {"name": "story", "value": "应急处置"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_emergency"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "14852-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_emergency"}]}