{"name": "困人事件标记误报", "status": "passed", "attachments": [{"name": "log", "source": "cef1689e-6f9b-4495-8f37-3c08d59dae02-attachment.txt", "type": "text/plain"}], "start": 1692260239794, "stop": 1692260239921, "uuid": "3e78009c-ed8f-4fae-b866-a387301c32e2", "historyId": "ab566412ce2c9ed8e210215e4ae8a5dd", "testCaseId": "16b1c3c86243e1b02c591065644e1507", "fullName": "opsPC.test_emergency#test_update_deal_status_false_alarm_001", "labels": [{"name": "feature", "value": "运维管理平台"}, {"name": "story", "value": "应急处置"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_emergency"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "16680-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_emergency"}]}