{"name": "困人事件标记误报", "status": "passed", "attachments": [{"name": "log", "source": "cd2b6b9f-d9b1-4329-b6c0-10e5a8198295-attachment.txt", "type": "text/plain"}], "start": 1690256289009, "stop": 1690256289106, "uuid": "a857d48a-a1c9-4e75-8b9a-685e8ed5a0c9", "historyId": "ab566412ce2c9ed8e210215e4ae8a5dd", "testCaseId": "16b1c3c86243e1b02c591065644e1507", "fullName": "opsPC.test_emergency#test_update_deal_status_false_alarm_001", "labels": [{"name": "feature", "value": "运维管理平台"}, {"name": "story", "value": "应急处置"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_emergency"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "18760-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_emergency"}]}