{"name": "困人处置列表", "status": "passed", "attachments": [{"name": "log", "source": "ec191b49-0355-47e2-a9f6-dd130b72d849-attachment.txt", "type": "text/plain"}], "start": 1690185380641, "stop": 1690185380771, "uuid": "ba79d2ba-dab0-4a14-bf59-ab06bffd2ab0", "historyId": "e9533ca1bce9dcd222ffc25dce3a836e", "testCaseId": "1307c5a2fbf84e6aa7a4e7b10201eae2", "fullName": "opsPC.test_emergency#test_device_error_trapped_list_001", "labels": [{"name": "story", "value": "应急处置"}, {"name": "feature", "value": "运维管理平台"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_emergency"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "18100-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_emergency"}]}