{"name": "困人处置列表", "status": "passed", "attachments": [{"name": "log", "source": "a4616b37-29d7-4bff-b45c-3e75bb47effb-attachment.txt", "type": "text/plain"}], "start": 1692069123984, "stop": 1692069124125, "uuid": "563bf302-f407-4e6c-b8f0-c369c89bc2d4", "historyId": "e9533ca1bce9dcd222ffc25dce3a836e", "testCaseId": "1307c5a2fbf84e6aa7a4e7b10201eae2", "fullName": "opsPC.test_emergency#test_device_error_trapped_list_001", "labels": [{"name": "feature", "value": "运维管理平台"}, {"name": "story", "value": "应急处置"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_emergency"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "14880-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_emergency"}]}