{"name": "困人处置列表", "status": "passed", "attachments": [{"name": "log", "source": "e45f38b6-0947-49f9-a320-9a280b3deb13-attachment.txt", "type": "text/plain"}], "start": 1690253015151, "stop": 1690253015280, "uuid": "ac5b845c-77b2-4fff-acd7-6a67651d9a74", "historyId": "e9533ca1bce9dcd222ffc25dce3a836e", "testCaseId": "1307c5a2fbf84e6aa7a4e7b10201eae2", "fullName": "opsPC.test_emergency#test_device_error_trapped_list_001", "labels": [{"name": "feature", "value": "运维管理平台"}, {"name": "story", "value": "应急处置"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_emergency"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "18116-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_emergency"}]}