{"name": "困人处置列表-未知", "status": "passed", "attachments": [{"name": "log", "source": "a61327ab-d19c-43f1-bcee-15da865e9d60-attachment.txt", "type": "text/plain"}], "start": 1692689154760, "stop": 1692689155013, "uuid": "58b4cd02-fa27-4d1f-93e2-f53f8f6b2c9f", "historyId": "c16e0aac483c5cc5ea4df007421ff869", "testCaseId": "8649210a73733792a7b60d9aac38ca04", "fullName": "opsPC.test_emergency#test_device_error_trapped_list_008", "labels": [{"name": "story", "value": "应急处置"}, {"name": "feature", "value": "运维管理平台"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_emergency"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "13204-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_emergency"}]}