{"name": "困人处置列表-真实", "status": "passed", "attachments": [{"name": "log", "source": "61359b17-387b-494d-bf52-a55f037d50be-attachment.txt", "type": "text/plain"}], "start": 1690529619555, "stop": 1690529619777, "uuid": "b988ec82-fd40-4f6d-95d1-dd88b6568123", "historyId": "2c9991b785716977eb4cbbaa1f323277", "testCaseId": "792deb5b60e48cc51a654ad1e9657ccb", "fullName": "opsPC.test_emergency#test_device_error_trapped_list_003", "labels": [{"name": "feature", "value": "运维管理平台"}, {"name": "story", "value": "应急处置"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_emergency"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "11532-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_emergency"}]}