{"uuid": "65a88b5f-2143-40a8-b492-2317e9151002", "children": ["62860781-2994-4d21-96cf-a564cb9d4506"], "befores": [{"name": "device_version_update_setup", "status": "broken", "statusDetails": {"message": "requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n", "trace": "  File \"D:\\tool\\python\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\tool\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\tool\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\work\\jishiyu\\Interface_jsy\\test_case\\opsPC\\test_deviceManage.py\", line 95, in device_version_update_setup\n    response = send_requests(method, apiurl, headers=headers, params=params)\n  File \"D:\\work\\jishiyu\\Interface_jsy\\apilist\\opsApi.py\", line 32, in send_requests\n    response = rq.request(method,url_api,data=data, params=params,headers=headers,files=files).json()\n  File \"D:\\tool\\python\\lib\\site-packages\\requests\\models.py\", line 976, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\n"}, "start": 1692178381104, "stop": 1692178381303}], "start": 1692178381104, "stop": 1692178381383}