{"name": "困人处置列表", "status": "passed", "attachments": [{"name": "log", "source": "308339db-1e87-4a5d-bc2d-eeb13e9c08ea-attachment.txt", "type": "text/plain"}], "start": 1692326134450, "stop": 1692326134959, "uuid": "748042a5-4c40-4bb9-8cdf-b88c8344d806", "historyId": "e9533ca1bce9dcd222ffc25dce3a836e", "testCaseId": "1307c5a2fbf84e6aa7a4e7b10201eae2", "fullName": "opsPC.test_emergency#test_device_error_trapped_list_001", "labels": [{"name": "feature", "value": "运维管理平台"}, {"name": "story", "value": "应急处置"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_emergency"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "8932-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_emergency"}]}