{"name": "困人处置列表", "status": "passed", "attachments": [{"name": "log", "source": "aa91fa28-8b17-4f6a-8de8-1a0fb1005205-attachment.txt", "type": "text/plain"}], "start": 1692689153153, "stop": 1692689153283, "uuid": "3f533ef7-ba49-45ed-99b9-e15cd50bf656", "historyId": "e9533ca1bce9dcd222ffc25dce3a836e", "testCaseId": "1307c5a2fbf84e6aa7a4e7b10201eae2", "fullName": "opsPC.test_emergency#test_device_error_trapped_list_001", "labels": [{"name": "story", "value": "应急处置"}, {"name": "feature", "value": "运维管理平台"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_emergency"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "13204-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_emergency"}]}