{"name": "困人事件回放", "status": "passed", "attachments": [{"name": "log", "source": "b4537cf4-3cb7-4a52-955d-3fefddede377-attachment.txt", "type": "text/plain"}], "start": 1690249611535, "stop": 1690249611587, "uuid": "302e2b5d-3c8e-443c-9782-e1c0a0d4d682", "historyId": "573010e86cab1a3d90647b98551bd886", "testCaseId": "8a4e3003043ec7852cf822ca71790ce0", "fullName": "opsPC.test_emergency#test_device_error_trapped_video_replay_001", "labels": [{"name": "story", "value": "应急处置"}, {"name": "feature", "value": "运维管理平台"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_emergency"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "4716-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_emergency"}]}